# -*- mode: ruby -*-
# vim: set ft=ruby :
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

MACHINES = {
  :inetRouter => {
        :box_name => "almalinux/9",
        :vm_name => "inetRouter",
        :net => [
                   {type: "private_network", adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                   {type: "private_network", adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                   {type: "private_network", ip: '192.168.56.10', adapter: 8},
                ]
  },
  :centralRouter => {
        :box_name => "almalinux/9",
        :vm_name => "centralRouter",
        :net => [
                   {type: "private_network", adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                   {type: "private_network", adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                   {type: "private_network", ip: '192.168.255.9', netmask: "255.255.255.252", virtualbox__intnet: "office1-central", adapter: 6},
                   {type: "private_network", ip: '192.168.56.11', adapter: 8},
                ]
  },

  :office1Router => {
        :box_name => "almalinux/9",
        :vm_name => "office1Router",
        :net => [
                   {type: "private_network", ip: '192.168.255.10', netmask: "255.255.255.252", virtualbox__intnet: "office1-central", adapter: 2},
                   {type: "private_network", adapter: 3, auto_config: false, virtualbox__intnet: "vlan1"},
                   {type: "private_network", adapter: 4, auto_config: false, virtualbox__intnet: "vlan1"},
                   {type: "private_network", adapter: 5, auto_config: false, virtualbox__intnet: "vlan2"},
                   {type: "private_network", adapter: 6, auto_config: false, virtualbox__intnet: "vlan2"},
                   {type: "private_network", ip: '192.168.56.20', adapter: 8},
                ]
  },

  :testClient1 => {
        :box_name => "almalinux/9",
        :vm_name => "testClient1",
        :net => [
                   {type: "private_network", adapter: 2, auto_config: false, virtualbox__intnet: "vlan1"},
                   {type: "private_network", ip: '192.168.56.21', adapter: 8},
                ]
  },

  :testServer1 => {
        :box_name => "almalinux/9",
        :vm_name => "testServer1",
        :net => [
                   {type: "private_network", adapter: 2, auto_config: false, virtualbox__intnet: "vlan1"},
                   {type: "private_network", ip: '192.168.56.22', adapter: 8},
            ]
  },

  :testClient2 => {
        :box_name => "ubuntu/jammy64",
        :vm_name => "testClient2",
        :net => [
                   {type: "private_network", adapter: 2, auto_config: false, virtualbox__intnet: "vlan2"},
                   {type: "private_network", ip: '192.168.56.31', adapter: 8},
                ]
  },

  :testServer2 => {
        :box_name => "ubuntu/jammy64",
        :vm_name => "testServer2",
        :net => [
                   {type: "private_network", adapter: 2, auto_config: false, virtualbox__intnet: "vlan2"},
                   {type: "private_network", ip: '192.168.56.32', adapter: 8},
                ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      box.vm.box_version = boxconfig[:box_version] if boxconfig[:box_version]

      config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
       end

      boxconfig[:net].each do |netconf|
        box.vm.network netconf[:type], **netconf.reject { |k| k == :type }
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        chmod 600 ~root/.ssh/authorized_keys
      SHELL
    end
  end
end