MACHINES = {
  :"kernel-update" => {
    :box_name => "centos8s2",
    :cpus => 2,
    :memory => 4096,
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      
      # Включение shared folders с нужными опциями
      box.vm.synced_folder ".", "/vagrant", 
        type: "virtualbox",
        mount_options: ["dmode=777", "fmode=666"],
        disabled: false
      
      # Проверка и установка зависимостей для сборки ядра
      box.vm.provision "shell", inline: <<-SHELL
        # Установка зависимостей для сборки ядра
        sudo dnf install -y git make gcc bc bison flex elfutils-libelf-devel openssl-devel perl rsync ncurses-devel
        
        # Скачивание исходников ядра (возьмем стабильную LTS версию)
        KERNEL_VERSION=6.15.9
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$KERNEL_VERSION.tar.xz
        tar -xvf linux-$KERNEL_VERSION.tar.xz
        cd linux-$KERNEL_VERSION
        
        # Копирование текущей конфигурации
        cp /boot/config-$(uname -r) .config
        
        # Настройка конфигурации для VirtualBox
        make olddefconfig
        scripts/config --enable CONFIG_FUSE_FS
        scripts/config --enable CONFIG_VBOXSF_FS
        
        # Сборка ядра (параллельная с использованием всех ядер)
        make -j$(nproc)
        
        # Установка нового ядра
        sudo make modules_install
        sudo make install
        
        # Обновление GRUB
        sudo grub2-mkconfig -o /boot/grub2/grub.cfg
        sudo grub2-set-default 0
      SHELL
      
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
        # Включение поддержки виртуализации для сборки ядра
        v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      end
    end
  end
end